# NumPy Array and Vectorization

In [1]:
# convention for importing numpy
import numpy as np 

arr = [6, 7, 8 , 9] 
print(type(arr)) # prints <class 'list'> 

<class 'list'>


In [4]:
a = np.array(arr) 
print(type(a)) # print <class ' numpy.ndarray'> 
print(a.shape) # prints (4,) - a is a 1d array with 4 items
print(a.dtype) #prints int64 

#get the dimension of a with ndim 
print(a.ndim) 

<class 'numpy.ndarray'>
(4,)
int32
1


In [8]:
b = np.array([[1,2,3], [4,5,6]]) 
print(b) # prints [[1 2 3]
         ##        [4 5 6]]
print(b.ndim) #prints (2,3) - b a 2d array with 2 rows and 3 columns 

[[1 2 3]
 [4 5 6]]
2


In [11]:
import numpy as np 

arr = [6, 7, 8 , 9] 
print(type(arr)) # prints <class 'list'> 

a = np.array(arr)
print(type(a)) # prints <class 'numpy.ndarray'> 
print(a.shape) # prints (4,) - a is a 1d array with 4 items
print(a.dtype) #prints int64 

#get the dimension of a with ndim 
print(a.ndim) 

b = np.array([[1,2,3], [4,5,6]]) 
print(b) # prints [[1 2 3]
         ##        [4 5 6]]
print(b.ndim) #prints (2,3) - b a 2d array with 2 rows and 3 columns 

<class 'list'>
<class 'numpy.ndarray'>
(4,)
int32
1
[[1 2 3]
 [4 5 6]]
2


In [14]:
# a 2x3 array with random values 
np.random.random((2,3))

# a 2x3 array of zeros 
np.zeros((2,3))

# a 2x3 array of ones 
np.ones((2,3)) 

# a 3x3 identity matrix 
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
import numpy as np

c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

c + d = array([[13., 13., 13.],
               [10., 10., 10.]])

c * d = array([[36., 40., 42.],
               [9., 16., 21.]])

5 / d = array([[1.25      , 1.        , 0.83333333],
               [0.55555556, 0.625     , 0.71428571]])

c ** 2 = array([[81., 64., 49.],
                [1., 4., 9.]])



In [24]:
a[0] = 6
a[3] = 9 
b[0, 0] = 1
b[1, 2] = 6 
c[0, 1] = 8


In [23]:
import numpy as np

c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

sum_cd = c + d
product_cd = c * d
division_5d = 5 / d
power_c2 = c ** 2

# Now if you want to print the results, you can do so by using the print function:
print("c + d =\n", sum_cd)
print("c * d =\n", product_cd)
print("5 / d =\n", division_5d)
print("c ** 2 =\n", power_c2)


c + d =
 [[13. 13. 13.]
 [10. 10. 10.]]
c * d =
 [[36. 40. 42.]
 [ 9. 16. 21.]]
5 / d =
 [[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]
c ** 2 =
 [[81. 64. 49.]
 [ 1.  4.  9.]]


In [25]:
import numpy as np

# Assuming d is already defined somewhere above this line and has at least two rows and two columns.
# d[1, 0:2] = np.array([9., 8.])

# Correct way to define e and perform slicing
e = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]])

# Correct slicing
sliced_e = e[:3, :2]

# Printing sliced array
print("Sliced e =\n", sliced_e)


Sliced e =
 [[10 11]
 [13 14]
 [16 17]]


In [26]:
import numpy as np

# Assuming 'e' is a previously defined numpy array of appropriate shape.
# Integer indexing example
# The indices must be provided in lists or arrays for each dimension.
integer_indexed = e[[2, 0, 3, 1], [2, 1, 0, 2]]

# Boolean indexing example
# The condition generates a boolean array that is then used to index the 'e' array.
boolean_indexed = e[e > 15]

# Printing results
print("Integer indexed e =\n", integer_indexed)
print("Boolean indexed e (values greater than 15) =\n", boolean_indexed)


Integer indexed e =
 [18 11 19 15]
Boolean indexed e (values greater than 15) =
 [16 17 18 19 20 21]


In [27]:
import numpy as np

# Example arrays for demonstration
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Mathematical functions
sum_a = np.sum(a)
mean_a = np.mean(a)
std_a = np.std(a)
min_a = np.min(a)

# You would need a 2D array for correlation coefficient
# For example purposes, let's create a simple 2D array
c = np.array([[1, 2, 3], [5, 6, 7]])
corrcoef_c = np.corrcoef(c)

print("Sum of a:", sum_a)
print("Mean of a:", mean_a)
print("Standard deviation of a:", std_a)
print("Minimum of a:", min_a)
print("Correlation coefficient matrix of c:")
print(corrcoef_c)

Sum of a: 15
Mean of a: 3.0
Standard deviation of a: 1.4142135623730951
Minimum of a: 1
Correlation coefficient matrix of c:
[[1. 1.]
 [1. 1.]]


In [28]:
# Comparing arrays
are_equal = a == b
greater_than = a > b
less_than = a < b

print("Arrays equal:", are_equal)
print("Elements in a greater than b:", greater_than)
print("Elements in a less than b:", less_than)

Arrays equal: [False False  True False False]
Elements in a greater than b: [False False False  True  True]
Elements in a less than b: [ True  True False False False]


In [29]:
# File Input and Output
# Saving array 'a' to a binary .npy file
np.save('array_a.npy', a)

# Loading the array from the .npy file
loaded_a = np.load('array_a.npy')
print("Loaded array a from .npy file:", loaded_a)

Loaded array a from .npy file: [1 2 3 4 5]


In [30]:
# saving array 'a' to a text 

np.savetxt('array_a.txt', a)

In [31]:
# Loading the array from the text file
loaded_a_txt = np.loadtxt('array_a.txt')
print("Loaded array a from text file:", loaded_a_txt)

Loaded array a from text file: [1. 2. 3. 4. 5.]
